"""The mutation study must exist, be readable, and show that the checks bite.

A suite of assertions that never fails proves nothing. `mutate.py` corrupts the
input on purpose and records how many assertions die. This check refuses to let
the paper ship without that evidence, and refuses to accept it if any mutant
survived untouched -- a mutant that kills nothing is a hole in the suite.

The report is generated by `mutate.py` and read here. The numbers it contains
are frozen claims like any other, so a stale report fails `check_40` too.
"""

from checks import check
from src import manuscript

ORDER = 95
NAME = "Mutation evidence present and every mutant killed something"
GATE = False


def run(context):
    present = manuscript.exists(manuscript.MUTATION_REPORT)
    results = [check(
        "MUT-report-present",
        present,
        "%s is missing; run mutate.py" % manuscript.MUTATION_REPORT,
    )]
    if not present:
        return results

    summary = context.mutation_summary
    results.append(check(
        "MUT-report-parses",
        all(key in summary for key in ("n_mutants", "min_checks_killed", "max_checks_killed")),
        "%s does not carry a machine-readable summary block" % manuscript.MUTATION_REPORT,
    ))
    if "min_checks_killed" not in summary:
        return results

    results.append(check(
        "MUT-all-mutants-killed",
        summary["min_checks_killed"] >= 1,
        "at least one mutant survived the whole suite; the checks do not cover "
        "the corruption it introduced",
    ))

    results.append(check(
        "MUT-study-nonempty",
        summary["n_mutants"] >= 1,
        "the mutation study ran no mutants",
    ))

    return results
